const STORE_KEY='qiyue-geography-final-self-study-v1';
let current=null,revealed=false,currentScored=false,selectedChoiceKey='';
const $=id=>document.getElementById(id);const byId=new Map(QUESTIONS.map(q=>[q.id,q]));const state=loadState();
function loadState(){let raw={};try{raw=JSON.parse(localStorage.getItem(STORE_KEY))||{}}catch{}return{answered:+(raw.answered||0),correct:+(raw.correct||0),wrong:raw.wrong&&typeof raw.wrong==='object'?raw.wrong:{},seen:raw.seen&&typeof raw.seen==='object'?raw.seen:{},mastered:raw.mastered&&typeof raw.mastered==='object'?raw.mastered:{},queues:raw.queues&&typeof raw.queues==='object'?raw.queues:{},lastQuestionByKey:raw.lastQuestionByKey&&typeof raw.lastQuestionByKey==='object'?raw.lastQuestionByKey:{}}}
function save(){localStorage.setItem(STORE_KEY,JSON.stringify(state));renderStats();renderWrongList()}function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function unique(a){return[...new Set(a)].sort((x,y)=>x.localeCompare(y,'zh-Hant'))}function shuffle(a){const c=[...a];for(let i=c.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[c[i],c[j]]=[c[j],c[i]]}return c}function hash(t){let h=0;for(let i=0;i<t.length;i++)h=(Math.imul(31,h)+t.charCodeAt(i))|0;return(h>>>0).toString(36)}function isChoice(q){return Array.isArray(q?.choices)&&q.choices.length>0}
function init(){const units=['全部範圍',...unique(QUESTIONS.map(q=>q.subject))];$('subjectSelect').innerHTML=units.map(s=>`<option value="${s==='全部範圍'?'':esc(s)}">${esc(s)}</option>`).join('');renderTypeOptions();$('subjectSelect').addEventListener('change',()=>{renderTypeOptions();pickQuestion()});$('typeSelect').addEventListener('change',pickQuestion);$('modeSelect').addEventListener('change',pickQuestion);$('newQuestion').addEventListener('click',pickQuestion);$('nextQuestion').addEventListener('click',pickQuestion);$('revealAnswer').addEventListener('click',reveal);$('markCorrect').addEventListener('click',()=>mark(true));$('markWrong').addEventListener('click',()=>mark(false));$('resetStats').addEventListener('click',()=>{if(confirm('確定清除本機統計、錯題、熟練與本輪隨機題列？')){state.answered=0;state.correct=0;state.wrong={};state.seen={};state.mastered={};state.queues={};state.lastQuestionByKey={};save();pickQuestion()}});renderStats();renderWrongList();pickQuestion()}
function renderTypeOptions(){const subj=$('subjectSelect').value;const list=QUESTIONS.filter(q=>!subj||q.subject===subj);const types=['全部題型',...unique(list.map(q=>q.type))];$('typeSelect').innerHTML=types.map(t=>`<option value="${t==='全部題型'?'':esc(t)}">${esc(t)}</option>`).join('')}
function filtered(){const subj=$('subjectSelect').value,type=$('typeSelect').value,mode=$('modeSelect').value;let list=QUESTIONS.filter(q=>(!subj||q.subject===subj)&&(!type||q.type===type));if(mode==='wrong'){const ids=new Set(Object.keys(state.wrong).filter(id=>state.wrong[id]>0));list=list.filter(q=>ids.has(q.id))}return list}
function activePool(list){if($('modeSelect').value==='wrong')return list;const notMastered=list.filter(q=>!state.mastered[q.id]);return notMastered.length?notMastered:list}function queueKey(pool){const subj=$('subjectSelect').value||'all-subjects',type=$('typeSelect').value||'all-types',mode=$('modeSelect').value||'all';return`${mode}::${subj}::${type}::${hash(pool.map(q=>q.id).sort().join('|'))}`}
function nextFromQueue(list){const pool=activePool(list),ids=pool.map(q=>q.id);if(!ids.length)return null;const key=queueKey(pool),valid=new Set(ids);let queue=Array.isArray(state.queues[key])?state.queues[key].filter(id=>valid.has(id)):[];if(!queue.length){queue=shuffle(ids);const last=state.lastQuestionByKey[key];if(queue.length>1&&queue[0]===last)[queue[0],queue[1]]=[queue[1],queue[0]]}const id=queue.shift();state.queues[key]=queue;state.lastQuestionByKey[key]=id;return byId.get(id)||pool.find(q=>q.id===id)||null}function prune(id){for(const k of Object.keys(state.queues))if(Array.isArray(state.queues[k]))state.queues[k]=state.queues[k].filter(x=>x!==id)}
function pickQuestion(){const list=filtered();current=nextFromQueue(list);revealed=false;currentScored=false;selectedChoiceKey='';renderQuestion();save()}function renderQuestion(){if(!current){$('qStem').textContent='這個篩選目前沒有題目。若選「只練錯題」，代表目前沒有錯題。';$('choices').innerHTML='';$('answerPanel').hidden=true;return}$('qSubject').textContent=current.subject;$('qType').textContent=current.type;$('qSkill').textContent=current.skill||'地理概念';$('qStem').textContent=current.stem;$('choices').innerHTML=isChoice(current)?current.choices.map(c=>`<button class="choice" data-key="${esc(c.key)}">${esc(c.key)}. ${esc(c.text)}</button>`).join(''):'';document.querySelectorAll('.choice').forEach(btn=>btn.addEventListener('click',()=>answerChoice(btn.dataset.key)));$('answerPanel').hidden=true;$('qFeedback').hidden=true;$('qFeedback').className='feedback';$('nextQuestion').hidden=true;$('nextQuestion').disabled=true;$('revealAnswer').disabled=isChoice(current);$('markCorrect').disabled=isChoice(current);$('markWrong').disabled=isChoice(current);$('qAnswer').textContent='';$('qExplanation').innerHTML='';$('qSource').textContent=current.source||''}
function answerChoice(key){if(!current||currentScored)return;selectedChoiceKey=key;const ok=key===current.answer;document.querySelectorAll('.choice').forEach(btn=>{btn.disabled=true;if(btn.dataset.key===current.answer)btn.classList.add('correct');if(btn.dataset.key===key&&!ok)btn.classList.add('wrong')});score(ok);showAnswer(ok)}function reveal(){if(!current)return;revealed=true;$('markCorrect').disabled=false;$('markWrong').disabled=false;showAnswer(null)}function mark(ok){if(!current)return;if(!revealed)reveal();if(currentScored)return;score(ok);showAnswer(ok)}function score(ok){if(currentScored)return;currentScored=true;state.answered++;state.seen[current.id]=(state.seen[current.id]||0)+1;if(ok){state.correct++;state.mastered[current.id]=1;delete state.wrong[current.id];prune(current.id)}else{state.wrong[current.id]=(state.wrong[current.id]||0)+1;delete state.mastered[current.id]}save()}
function fallbackChoiceExplain(q,c){const right=c.key===q.answer,skill=q.skill||'',text=c.text||'';if(right)return`此選項符合題幹要求。關鍵是「${text}」。`;if(skill.includes('氣候'))return'此選項的氣候位置、降水季節或成因不符合題幹。';if(skill.includes('地形'))return'此選項的地形、河川或板塊作用判斷不符合題幹。';if(skill.includes('族群'))return'此選項的族群、語言、宗教或殖民背景判斷不符合題幹。';if(skill.includes('農礦'))return'此選項的農礦產品、外銷或殖民地式經濟判斷不符合題幹。';if(skill.includes('經濟'))return'此選項的經濟優勢或發展挑戰判斷不符合題幹。';return'此選項不是本題最符合題幹的答案。'}
function answerHtml(q){if(!isChoice(q))return esc(q.explanation||'翻答案後，請確認自己能說出關鍵因果。');const rows=q.choices.map(c=>{const right=c.key===q.answer,picked=selectedChoiceKey===c.key,cls=right?'correct':(picked&&!right?'selectedWrong':''),tag=right?'✅ 正確答案':(picked?'❌ 你選的答案':'— 不是答案');const detail=q.choiceExplanations?.[c.key]||fallbackChoiceExplain(q,c);return`<div class="choice-row ${cls}"><b>${esc(c.key)}. ${tag}</b><div>${esc(detail)}</div></div>`}).join('');return`${esc(q.explanation||'請比對題幹條件與正確選項。')}<div class="choice-explain">${rows}</div>`}
function showAnswer(ok){if(!current)return;const ans=isChoice(current)?`${current.answer}. ${(current.choices.find(c=>c.key===current.answer)||{}).text||''}`:current.answer;$('qAnswer').textContent=ans;$('qExplanation').innerHTML=answerHtml(current);$('qSource').textContent=current.source||'';if(ok!==null){$('qFeedback').hidden=false;$('qFeedback').textContent=ok?'答對了，這題先排除，等未熟題做完再回來複習。':'這題先加入錯題，之後可切到「只練錯題」。';$('qFeedback').className='feedback '+(ok?'ok':'bad')}else{$('qFeedback').hidden=true}$('answerPanel').hidden=false;$('nextQuestion').hidden=false;$('nextQuestion').disabled=false;setTimeout(()=>$('answerPanel').scrollIntoView({behavior:'smooth',block:'nearest'}),30)}
function renderStats(){const wrongTotal=Object.values(state.wrong).reduce((a,b)=>a+Number(b||0),0),rate=state.answered?Math.round(state.correct/state.answered*100):0,mastered=Object.keys(state.mastered).length;$('statAnswered').textContent=state.answered;$('statCorrect').textContent=state.correct;$('statWrong').textContent=wrongTotal;$('statRate').textContent=rate+'%';$('statMastered').textContent=mastered}
function renderWrongList(){const ids=Object.keys(state.wrong).filter(id=>state.wrong[id]>0);if(!ids.length){$('wrongList').innerHTML='<div class="wrong-item">目前沒有錯題。答錯後會自動出現在這裡。</div>';return}$('wrongList').innerHTML=ids.slice(0,18).map(id=>{const q=byId.get(id);return`<div class="wrong-item"><b>${esc(q?.type||'題目')}｜錯 ${state.wrong[id]} 次</b><div>${esc((q?.stem||id).slice(0,90))}${(q?.stem||'').length>90?'…':''}</div><button data-jump="${esc(id)}">直接練這題</button></div>`}).join('');document.querySelectorAll('[data-jump]').forEach(btn=>btn.addEventListener('click',()=>{current=byId.get(btn.dataset.jump);revealed=false;currentScored=false;selectedChoiceKey='';renderQuestion()}))}
document.addEventListener('DOMContentLoaded',init);
